
export const INITIAL_IDPS = [
  { 
    id: '1', 
    name: 'أحمد المحمد', 
    location: 'مخيم الأمل', 
    familySize: 5, 
    status: 'Served', 
    lastAidDate: '2023-10-25', 
    needs: ['غذاء', 'دواء'],
    idNumber: '123456789',
    phone: '059000000',
    birthDate: '1985-05-10',
    addressBefore: 'غزة - الرمال',
    gender: 'ذكر',
    role: 'nazih',
    maritalStatus: 'متزوج',
    healthStatus: 'مُعافى',
    housingStatus: 'هدم كُلي',
    shelterType: 'خيمة',
    shelterNumber: 'A-101',
    familyMembers: [],
    externalDependents: [],
    docs: { profilePic: 'https://picsum.photos/seed/1/300' }
  },
  { 
    id: '2', 
    name: 'سارة العبدالله', 
    location: 'حي الكرامة', 
    familySize: 3, 
    status: 'Critical', 
    lastAidDate: '2023-09-12', 
    needs: ['ماء', 'خيمة'],
    idNumber: '987654321',
    phone: '059111111',
    birthDate: '1990-08-20',
    addressBefore: 'خانيونس - البلد',
    gender: 'أُنثى',
    role: 'nazih',
    maritalStatus: 'أرملة',
    healthStatus: 'مريض مُزمن',
    housingStatus: 'هدم جُزئي',
    shelterType: 'خيمة',
    shelterNumber: 'B-205',
    familyMembers: [],
    externalDependents: [],
    docs: { profilePic: 'https://picsum.photos/seed/2/300' }
  },
  { 
    id: '3', 
    name: 'محمد الخالد', 
    location: 'مخيم النور', 
    familySize: 7, 
    status: 'Pending', 
    lastAidDate: '2023-11-01', 
    needs: ['غذاء', 'ملابس'],
    idNumber: '456789123',
    phone: '059222222',
    birthDate: '1978-02-15',
    addressBefore: 'جباليا - المعسكر',
    gender: 'ذكر',
    role: 'nazih',
    maritalStatus: 'متزوج',
    healthStatus: 'مُعافى',
    housingStatus: 'منطقة قتال',
    shelterType: 'صف',
    shelterNumber: 'C-05',
    familyMembers: [],
    externalDependents: [],
    docs: { profilePic: 'https://picsum.photos/seed/3/300' }
  },
];

export const AID_TYPES = [
  { id: 'food-parcel', label: 'طرد غذائي', icon: 'fa-box-open' },
  { id: 'health-parcel', label: 'طرد صحي', icon: 'fa-hand-holding-medical' },
  { id: 'clothes', label: 'ملابس', icon: 'fa-shirt' },
  { id: 'shoes', label: 'أحذية', icon: 'fa-shoe-prints' },
  { id: 'lighting', label: 'إنارة', icon: 'fa-lightbulb' },
  { id: 'flour', label: 'طحين', icon: 'fa-wheat-awn' },
  { id: 'meat-fish', label: 'لحوم و أسماك', icon: 'fa-fish' },
  { id: 'meals', label: 'وجبات', icon: 'fa-utensils' },
  { id: 'kitchenware', label: 'أدوات منزلية', icon: 'fa-blender' },
  { id: 'milk', label: 'حليب', icon: 'fa-baby-bottle' },
  { id: 'pampers', label: 'بامبرز', icon: 'fa-baby' },
  { id: 'milk-pampers', label: 'حليب و بامبرز', icon: 'fa-kit-medical' },
  { id: 'money', label: 'نقود', icon: 'fa-money-bill-wave' },
];
